# Generated by Django 4.1.2 on 2022-11-03 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={'verbose_name': 'Heroe', 'verbose_name_plural': 'Heroes'},
        ),
    ]
